// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application"

import InfiniteScrollController from "./infinite_scroll_controller"
import InlineEditController from "./inline_edit_controller"
import SearchController from "./search_controller"
import RowClickController from "./rowclick_controller"
import ArrowKeyController from "./arrowkeys_controller"
import ConfirmController from "./confirm_controller"
import DropDownController from "./dropdown_controller"

application.register("infinite-scroll", InfiniteScrollController)
application.register("inline-edit", InlineEditController)
application.register("search", SearchController)
application.register("rowclick", RowClickController)
application.register("arrowkeys", ArrowKeyController)
application.register("confirm", ConfirmController)
application.register("dropdown", DropDownController)